### ISSUE TITLE
Bug in Tree Constructor

### ISSUE THREAD

**Issue by icomefromthenet** [BlueM/Tree#1]
```php
 public function __construct(array $data, array $options = array())
    {
        $this->options = array_change_key_case($options, CASE_LOWER);
        if (!isset($this->options['rootid'])) {
            $this->options['rootid'] = 0;
        }

        $this->build($data, $options);
    }

```

Your changing the case of the options index but passing down the original options , should be

```php
 $this->build($data, $this->options);
```

**Comment by BlueM** [comment]
It is not a bug, as `build()` only accepts 1 argument. I.e. it doesn’t care for the passed array, but uses `$this->options`.

Nevertheless, thanks for bringing this to my attention. It looks like I forgot to remove the 2nd argument after some refactoring.
