### ISSUE TITLE
tree with max 3 children for each node

### ISSUE THREAD

**Issue by pws2016** [BlueM/Tree#15]
Hello,
i have mysql table structured for tree where each node have maximum 3 nodes in each level.
Example node1 is in row=1 & column=1
node 1 has 3 childrens where  row=2 & column=1,=2, =3 
next row is row=3 and have 9 possibles of column from col=1 to col=9

How i can use your code to insert new node in his right position if i know the parent
Exmaple if i want insert new node for parent node1(row=1, col=1) the logic must be row=3 & col=1 

in my db structure each node saved in 1 record with data: id, id_parent, row, column,id_reffer

id_parent is the parent id of direct sub level
id_reffer is the parent id first level

Can help me? Thanks

**Comment by BlueM** [comment]
If I understand correctly, each table row holds more than 1 node. This approach is not compatible with my library, therefore it will not be of any help. (And I would not recommend doing it the way you describe, as to me it seems inflexible, and it makes it harder to treat all the rows generically.)
