### ISSUE TITLE
Getting whole tree as JSON object?

### ISSUE THREAD

**Issue by roberttolton** [BlueM/Tree#16]
Hi,

Sorry if I'm missing something - but I have an array of arrays, passed into the Tree constructor - ids and parent ids set correctly, not getting any errors.

But when I json_encode the result.. it's just a flat array as it was when I passed it? There's no hierarchy, no nesting of nodes?

**Comment by BlueM** [comment]
Both the tree and the node class implement `\JsonSerializable` (see PHP manual), with simple default implementations for the `jsonSerialize()` method which will result in the behaviour you describe. (And which, BTW, is structured in a way that, when unserialized, you can pass it back in to the constructor.) If you want to customize the behavior, you can subclass the tree and/or node class and overwrite the `jsonSerialize()` method.

**Comment by roberttolton** [comment]
Thanks for the reply,

If they already implement it, why when I json_encode() the tree is it un-hierarchical?

Would you mind a brief example, just so I can compare?

I’m doing this within a plug-in of an existing CMS.

**Comment by BlueM** [comment]
If you look at the two `jsonSerialize()` implementations, you will see why it is not hierarchical. Needs can differ when serializing to JSON – not everybody might need the hierarchy in that situation.

The question regarding the use case in the CMS you mention is: does the tree instance already exist (has already been created by the CMS)? Or do you create the tree instance in your plugin?

**Comment by roberttolton** [comment]
I need to create the tree instance myself, I’m querying an external database. I’ve got the data in a flat array with all the right properties.

**Comment by roberttolton** [comment]
So I tried doing this in a separate Laravel app, but I couldn't get past this error:

```
Declaration of App\Custom\Tree::createNode($id, $parent, array $properties) must be compatible with BlueM\Tree::createNode($id, $parent, array $properties): BlueM\Tree\Node in /vagrant/app/Custom/Tree.php
```

Tree.php
```
<?php

namespace App\Custom;

use App\Custom\Node;

class Tree extends \BlueM\Tree {

    protected function createNode($id, $parent, array $properties): Node
    {
        return new Node($id, $parent, $properties);
    }

    public function jsonSerialize()
    {
        return $this->getRootNodes();
    }

}
```

Node.php
```
<?php

namespace App\Custom;

use App\OldComment;

class Node extends \BlueM\Tree\Node {

    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'parent' => $this->parent,
            'body' => $this->body,
            'created_at', $this->created_at,
            'visible' => $this->visible,
            'user' => $this->user,
            'children' => OldComment::where('id', $this->id)->first()->children()
        ];
    }

}
```

Both functions require the same parameters (copied from `src`) so I'm unsure what it's got issue with.

**Comment by BlueM** [comment]
Your `Tree` subclass returns a `Node`, which is a `App\Custom\Node` instance – and this violates the `BlueM\Node` return type hint from the superclass. It should work like this:

    protected function createNode($id, $parent, array $properties): \BlueM\Tree\Node

To make things more implicit (and if you are using PhpDoc doc comment), you could add this to the docblock:

    @return \App\Custom\Node

**Comment by roberttolton** [comment]
Thanks @BlueM , that's resolve that issue. However I'm now getting:
```
Undefined property: body
```
I'm guessing because of the properties i'm assigning in my Node class? When you mentioned about setting the attributes I wanted, was this not the right way to do it?

**Comment by roberttolton** [comment]
I edited it to the following, which seems silly since I already have all this data in the array that I'm giving `Tree` for processing:

```
<?php

namespace App\Custom;

use App\OldComment;

class Node extends \BlueM\Tree\Node {

    public function jsonSerialize()
    {
        $comment = OldComment::where('id', $this->id)->first();

        if ($comment) {
            $children = OldComment::where('id', $this->id)->first()->children();
        } else {
            $children = array();
        }

        return [
            'id' => $this->id,
            'parent' => $this->parent,
            'body' => ( $comment ? $comment->body : '' ),
            'created_at' => ( $comment ? $comment->created_at : '' ),
            'visible' => ( $comment ? $comment->visible : '' ),
            'children' => $children
        ];
    }

}
```

With this, I do get `children` but no deeper than one level. Any ideas?

**Comment by roberttolton** [comment]
Have also tried this:

```
<?php

namespace App\Custom;

use App\OldComment;
use Illuminate\Support\Facades\Log;

class Node extends \BlueM\Tree\Node {

    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'parent' => $this->parent,
            'body' => ( isset($this->properties['body']) ? $this->properties['body'] : '' ),
            'created_at' => ( isset($this->properties['created_at']) ? $this->properties['created_at'] : '' ),
            'visible' => ( isset($this->properties['visible']) ? $this->properties['visible'] : '' ),
            'children' => $this->children
        ];
    }

}
```

But the strange thing is, adding `$this->children` breaks my entire script, with no errors.

I'm setting my data like so:

```
if ($post->comments) {

    foreach ($post->comments as $key => $comment) {

        $parent = 0;

        if (strpos($comment->ancestry, '/') !== false) {
            $ancestryElements = explode('/', $comment->ancestry);
            $parent = end($ancestryElements);
        } else if (!is_null($comment->ancestry)) {
            $parent = $comment->ancestry;
        }

        $commentData = [
            'id' => $comment->id,
            'parent' => $parent,
            'body' => $comment->body,
            'created_at' => $comment->created_at,
            'visible' => $comment->visible,
            'user' => ( $comment->user ? [
                'id' => $comment->user->id,
                'username' => $comment->user->username,
                'email' => ( $comment->user->email ? $comment->user->email : '' ),
                'banned' => $comment->user->banned
            ] : [] )
        ];

        array_push($commentsData, $commentData);

    }

    $commentsData = new Tree($commentsData, ['rootId' => 0, 'id' => 'id', 'parent' => 'parent']);
    $commentsIncluded = true;

}
```

**Comment by roberttolton** [comment]
To solve the circular reference, I had to remove the 'parent' attribute from my Node class:
```
<?php

namespace App\Custom;

class Node extends \BlueM\Tree\Node {

    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'body' => ( isset($this->properties['body']) ? $this->properties['body'] : '' ),
            'created_at' => ( isset($this->properties['created_at']) ? $this->properties['created_at'] : '' ),
            'visible' => ( isset($this->properties['visible']) ? $this->properties['visible'] : '' ),
            'children' => ( $this->id != 0 ? $this->getChildren() : 0 )
        ];
    }

}
```
The tree now serialises correctly!

**Comment by BlueM** [comment]
You commented too fast for me to help … So all in all the problem is solved now, right?

BTW: you can replace some of those `isset(…)` constructs with the `??` operator.

**Comment by roberttolton** [comment]
All working now @BlueM, thanks!
