### ISSUE TITLE
Warning: json_encode(): recursion detected

### ISSUE THREAD

**Issue by crlsmtzprds** [BlueM/Tree#2]
I have an error when try to use json_encode with $tree->getRootNodes() 
This error can be hidden on my develop machine, but the server doesn't return nothign even error

**Comment by crlsmtzprds** [comment]
More info:
Googling I found something about trying change the "private" to "public" on your class but nothing happens. Maybe the name spaces? I don't know, but I see everything OK and it in some way it works on my local machine

Develop Machine
PHP API	20100412
PHP Version	5.4.30

Server
PHP API	20121113
PHP Version	5.5.9-1ubuntu4.11

pd.
If you're using Angular try to use angular-ui-tree is a very nice partner for you class

**Comment by BlueM** [comment]
Doing a quick test, I cannot reproduce this. But anyway, it makes more sense to control the JSON serialization yourself. I have just committed a version with an updated Readme, which includes a section on this topic: https://github.com/BlueM/Tree#controlling-json-serialization
