### ISSUE TITLE
[question] Is there an easy option to get only leaf nodes?

### ISSUE THREAD

**Issue by sabat24** [BlueM/Tree#20]
I didn't find any method to deal with my problem, but maybe do you know any easy modification I can make to get only leaf nodes from certain node or root?

**Comment by BlueM** [comment]
You could use the native `array_filter()` function with a callback which calls `$node->hasChildren()` on the node passed to the callback. Where to add that filtering, depends on your use case.

**Comment by sabat24** [comment]
It sounds that it should be fine enough for me. Thanks.
