### ISSUE TITLE
Format question : how to remove keys?

### ISSUE THREAD

**Issue by crouti** [BlueM/Tree#21]
Hi,
Thanks a lot for your wonderfull tool, it works very well. Nevertheless i have a question, after creating the tree and outputting the json hierarchical tree i have:

```
{
	"14": {
		"name": "2 Vous \u00eates",
		"title": "2 Vous \u00eates",
		"id": 2,
		"parent": 0,
		"children": {
			"0": {
				"name": "291 Etes-vous enceinte ?",
				"title": "291 Etes-vous enceinte ?",
				"id": 291,
				"parent": 2
			}
		}
	},
...
```

nevertheless, what i would like to obtain is somthing formatted like this:

```
{
 "name": "flare",
 "children": [
  {
   "name": "analytics",
   "children": [
    {
     "name": "cluster",
     "children": [
      {"name": "AgglomerativeCluster", "value": 3938},
      {"name": "CommunityStructure", "value": 3812},
      {"name": "HierarchicalCluster", "value": 6714},
      {"name": "MergeEdge", "value": 743}
     ]
    },
...
```

Is this possible ?
Thanks a lot

**Comment by BlueM** [comment]
Can’t tell, as the output you say you get does not look like what is typically generated by `HierarchicalTreeJsonSerializer`. Moreoever, your desired result has not very much to do with your actual result.

Anyway, if you have special needs, probably the best approach is to create an own serializer class. This could possibly be derived from `HierarchicalTreeJsonSerializer`and maybe the only thing you’d need to change is to remove the unwanted keys after https://github.com/BlueM/Tree/blob/master/src/Tree/Serializer/HierarchicalTreeJsonSerializer.php#L46

**Comment by crouti** [comment]
Ok thanks i will try this.
