### ISSUE TITLE
Handle malformed data

### ISSUE THREAD

**Issue by BAGELreflex** [BlueM/Tree#24]
Branched from discussion in: https://github.com/BlueM/Tree/issues/22

There exists a need to provide the ability to require validation of the provided data against an expected schema. By default, this should throw a new `MalformedDataException` (or similar) that stores information about which data attribute was missing or was otherwise malformed (i.e. key is a `string` instead of `int`), and in what way it was missing or malformed.

Performing malformed-data error checking should be enabled by default, but easily disabled. This is necessary to maintain performance on very large data sets that you know will have the right structure, such as the results of a well-written SQL statement using `PDO::FETCH_ASSOC` or similar.

Here is good discussion of options to validate an array against a schema: https://stackoverflow.com/questions/4036708/how-can-i-validate-the-structure-of-my-php-arrays

```php
// Somewhere around L216 in Tree.php, immediately inside of "foreach ($data as $rows)"
if ($this->malformedDataHandler !== false)
{
    $malformedData = array_diff(array_merge_recursive($arrCandidate, $arrModel), $arrModel));
    if (sizeof($malformedData))
    {
        call_user_func($this->malformedDataHandler, $row);
    }
}
```

I suggest putting it inside of the foreach so that the entire dataset doesn't have to be traversed twice. Once to get the `$malformedData`, if any, and then again to process it. It would be worth testing the tradeoff of checking for malformed data all at once, which would require a full re-iteration of the array, but that may end up actually being quicker than doing the `array_merge_recursive()` and `array_diff()` over every node inline.

The above suggestion would allow the user to set `$malformedDataHandler = false;` and disable checking/handling of the data vs the schema, and just allow PHP to log its `E_NOTICE` given that malformed data is encountered.

**Comment by BlueM** [comment]
I have to admit I don’t like the idea of having checking code in the package. The `Tree` class expects a certain data structure, and if it is called with something different, it’s a problem in the calling code (or the data the calling code consumed from elsewhere).

To put it differently: in the vast majority of cases, the data structure will be fine, but in those few cases where the data structure may be unreliable, the calling code will have to do something about it and choose the possible “proper” way to react. And that reaction cannot be anticipated by the library. It might be appropriate to throw an exception and stop processing, it might be sufficient to – as you suggest – emit an `E_NOTICE` or might be possible to fix the data at runtime. This decision is up to the calling code and the developer writing it. If you know or find out that the data is not structured in the way you expect it, you should take measures to handle it in your code.

However, I think that as a result of the discussions in #22, I will make the building mechanism more flexible / extendable, so in the end, if you really think you need to check the data in the `Tree` class, you will be able to extend it.
