### ISSUE TITLE
Calculate max depth

### ISSUE THREAD

**Issue by jdgrieco** [BlueM/Tree#29]
I noticed that there is a method that brings the level of the category.
Is there any way to return to the maximum depth?

**Comment by BlueM** [comment]
Not out of the box. One simple approach would be to get all nodes and iterate (or use `array_map()`) over them, calling `getLevel()` and finding the maximum level. However, this includes a bunch of method calls and depending on the amount and structure of the data this might be a bit slow.

A slight optimization could be to ignore any nodes with children (as none of these can be the node with the maximum level) when calling `getLevel()`:

```php
$maxLevel = max(
    array_map(
        function(\BlueM\Tree\Node $node) {
            return $node->getLevel();
        },
        array_filter(
            $tree->getNodes(),
            function(\BlueM\Tree\Node $node) {
                return !$node->hasChildren();
            }
        )
    )
);
```

Works, but I haven’t benchmarked anything.

**Comment by jdgrieco** [comment]
@BlueM, thanks.
