### ISSUE TITLE
own ID as parent ID exception

### ISSUE THREAD

**Issue by Viky-zhang** [BlueM/Tree#3]
My data:
```php
    {
        "id": "moblie_prj",
        "name": "my project",
        "parent": "0"
    },
```
this data throw exception `Node with ID $id references its own ID as parent ID` 

I found that Tree.php (line 188) compare of two string should be `===` instead of `==`.

**Comment by BlueM** [comment]
The reason I didn’t use `===` is that one the one hand, I would not have expected mixed datatypes for the IDs, but also as it might impose more work on users to make the input data type-safe.

However, if string IDs and numeric IDs are used in the same dataset, this is of course a bug. Thanks for reporting. On the other hand, simply using `===` in my opinion is not the optimal solution, as you can construct cases where the invalid parent reference might not be detected. See https://github.com/BlueM/Tree/commit/a75b2f7f57c81637e9e31b7f8408d8669bca36f6#diff-d6a892aa7d058c8f3e87ef9717e5cf4bR300 for a test where `===` would fail. Instead, I chose to use `(string)` typecasting plus `===`; the test is here: https://github.com/BlueM/Tree/commit/a75b2f7f57c81637e9e31b7f8408d8669bca36f6#diff-d6a892aa7d058c8f3e87ef9717e5cf4bR313

One more remark: when submitting a pull request, you should not change the project’s name in `composer.json`.
