### ISSUE TITLE
Send as json format

### ISSUE THREAD

**Issue by abohovhannisyan** [BlueM/Tree#30]
How to send children as json

**Comment by BlueM** [comment]
From your question, it’s completely unclear what you have tried, what you expected to get and what was the actual result.

There is info on generating JSON in the Readme (https://github.com/BlueM/Tree#json-serialization), but if that doesn’t answer your question, you need to be provide more details.

**Comment by BlueM** [comment]
Closed, as no feedback in almost two years.
