### ISSUE TITLE
 ErrorException Notice: Undefined index: parent

### ISSUE THREAD

**Issue by sorog** [BlueM/Tree#31]
ErrorException
in \vendor/bluem/tree/src/Tree.php (line 235)

230                $row = iterator_to_array($row);
231            }            
232          $this->nodes[$row[$this->idKey]] = $this->createNode(                
233        
234                $row[$this->idKey],
235                $row[$this->parentKey],
236                $row
237            );
238
239            if (empty($children[$row[$this->parentKey]])) {
240
![erreur Bluem tree](https://user-images.githubusercontent.com/17005422/87263424-a92dee00-c4ac-11ea-80a7-9e161b0b75f0.PNG)
                $children[$row[$this->parentKey]] = [$row[$this->idKey]];

Hello can you help me?

**Comment by BlueM** [comment]
Looks like somewhere in your input data the array key `parent` is missing. (Where `parent` is the default name for the parent node’s ID, which can be changed through options passed to `Tree`’s constructor.

**Comment by BlueM** [comment]
Closed due to lack of feedback
