### ISSUE TITLE
What is the benefit of lowercase keys in Node constructor ?

### ISSUE THREAD

**Issue by william-suppo** [BlueM/Tree#32]
Hi @BlueM,

When I serialized object in Tree with properties in camelCase, I cant unserialised them because ```Node``` change key to lowercase.

So I ask you : what is the benefit to change key to lowercase here ?
https://github.com/BlueM/Tree/blob/e520150cc713b4318c6ceae05d578462d930bc59/src/Tree/Node.php#L41

I try to change the line with that fix and it's works :

```php 
$this->properties = $properties;
```

**Comment by BlueM** [comment]
As you can see in the unit tests (https://github.com/BlueM/Tree/blob/e520150cc713b4318c6ceae05d578462d930bc59/tests/Tree/NodeTest.php#L322), the intention was to make the access case-insensitive. If you ask me why I wanted it to be case-insensitive in the first place, I guess I assumed (years ago when I wrote that code) that the majority of access to data would be via getters, and that functions in PHP are case-insensitive. (While I’m aware that one could argue that it is possible to access properties as `$node->foo`, and that the expectation could be that this is case-sensitive.)

May I ask which is your exact use case? You mention a “serialized” object – is that one serialized with `serialize()`, and where have you tried to unserialize it?

**Comment by simPod** [comment]
@BlueM access to data is not via getters on nowadays PHP.

**Comment by william-suppo** [comment]
Dont matter anymore, I build mynown package 😉
