### ISSUE TITLE
get Children by selected Level

### ISSUE THREAD

**Issue by Ali7med** [BlueM/Tree#42]
if can improve to get all children to selected level

**Comment by Ali7med** [comment]
i mean horizontal level like get all level  0 or 1 or can get selected level in all tree

**Comment by BlueM** [comment]
There is not a single “right” answer to this problem, as it depends on the level:

```php
// Level 1: all root Nodes
$level1Nodes = $tree->getRootNodes();

// Level 2: direct children of root nodes
$level2Nodes = array_merge(
    ... array_map(
        function (Node $rootNode) {
            return $rootNode->getChildren();
        },
        $tree->getRootNodes()
    )
);

// Level ≥ 3: filter nodes
$levelYouAreInterestedIn = 3;
$level3Nodes = array_filter(
    $tree->getNodes(),
    function(Node $node) use ($levelYouAreInterestedIn) {
        return $levelYouAreInterestedIn === $node->getLevel();
    }
);
```

Depending on the width and depth of the tree and the level, method 2 or 3 may be faster – I haven’t benchmarked this. For the top level, the first methode will be the best.

**Comment by Ali7med** [comment]
thanks.

**Comment by Ali7med** [comment]
if can update file readme to add  $node->getLevel() , thats will be awesome
