### ISSUE TITLE
Make 'parent' field configurable

### ISSUE THREAD

**Issue by alexandernst** [BlueM/Tree#5]
I work with data sets that come from other applications that I don't/can't control. The `parent` field of my data is `id_parent` and iterating over my data and renaming the filed seems a little bit of an overkill. Can you make the `parent` field configurable? (As in make it possible to specify what the `parent` field should be called).

**Comment by alexandernst** [comment]
Extra mile: can you make the `id` field configurable too?

**Comment by BlueM** [comment]
Both is simple to implement, but: I think there is no way to implement this in v1, as the `Node` class would have to be changed in a way which would break semantic versioning.

However, a slightly modernized v2 is overdue, so I’ve added this to my list for v2.

**Comment by wvdongen** [comment]
+1 for this feature.  Without this feature I can't use Tree.

@BlueM when is the v2 release planned?

**Comment by BlueM** [comment]
@wvdongen: Pretty soon, I’d guess within the next 2 weeks.

**Comment by BlueM** [comment]
@alexandernst: Should be usable for you now (finally!). See PHPDoc for `Tree`’s constructor. Basically, you should just have to pass `['parent' => 'id_parent']` as 2nd argument to the constructor.
