### ISSUE TITLE
getNodeById should return null if...

### ISSUE THREAD

**Issue by alexandernst** [BlueM/Tree#6]
... if nothing is found, instead of throwing an exception.

**Comment by BlueM** [comment]
I don’t agree. Returning `null` or throwing an exception is to some extent a matter of taste, but I’d say that when invoking `getNodeById()`, you expect the ID to exist, and if that isn’t the case, it justifies an exception.

Also, if you want to use `getNodeById()` without having to wrap it in `try`/`catch`, you can still subclass `Node` and overwrite `getNodeById()`, even with the current version.
